### ISSUE TITLE
Double lodash

### ISSUE THREAD

**Issue by donferi** [joeflateau/remix-superloader#1]
Hi, I've noticed that there is `lodash` and `lodash-es` as dependencies, is this expected?

Looks like you are only using `cloneDeepWith`, maybe the improt can change to `lodash/cloneDeepWith` or use the es version?

More info: https://lodash.com/per-method-packages

**Comment by joeflateau** [comment]
@donferi I'll revisit it... the per-method packages are deprecated as I understand it. and I had some errors when I didn't have the lodash-es dependency. I really only wanted lodash as a dep but had to add lodash-es to fix the error.

**Comment by joeflateau** [comment]
@donferi rollup generates cjs and esm bundles, the cjs bundles use lodash and the esm bundle uses lodash-es. I'm going to leave this as-is for now. Either way the remix build process is going to tree shake and you only end up with the lodash bits that you actually use
